backend:
  name: github
  repo: omushamotamashe-bot/estateprime
  branch: main
  site_domain: cozy-cendol-2c0fbf.netlify.app   # <-- ADD THIS LINE

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "_data/home.json"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Feature 1 Title", name: "feature1_title", widget: "string" }
          - { label: "Feature 1 Text", name: "feature1_text", widget: "text" }
